### ISSUE TITLE
Bootstrap not working as expected

### ISSUE THREAD

**Issue by KylSanAntonio** [GregYankovoy/vue-cli-plugin-bootstrap-vue#12]
I installed this plugin using vue cli 4.4.6 and I am able to use bootstrap's navbar and alert however, I noticed that it is not working properly. See below screenshots for your perusal.

**main.js**
![image](https://user-images.githubusercontent.com/65583602/89731389-40b93900-da79-11ea-8421-2ba055a83594.png)

**package.json**
![image](https://user-images.githubusercontent.com/65583602/89731468-c937d980-da79-11ea-9256-31407849fef1.png)

For bootstrap alert, it doesn't dismiss, here's the code:
![image](https://user-images.githubusercontent.com/65583602/89731371-2bdca580-da79-11ea-858c-3dd6727d3cfb.png)

Alert and navbar in action:
![vue](https://user-images.githubusercontent.com/65583602/89731434-8fff6980-da79-11ea-8b61-481f0866d6d7.gif)

**Comment by GregYankovoy** [comment]
Hi,

Thanks for the detailed information!  Bootstrap Vue uses custom vue components to surface all of the bootstrap 4 components.  While the css is shared between the two, all of the javascript is custom vue.

Please see the documentation for navbar and alert:
https://bootstrap-vue.org/docs/components/alert
https://bootstrap-vue.org/docs/components/navbar

For instance.  Rather than:
`<div class="alert alert-primary" role="alert">This is a primary alert—check it out!</div>`

You should use:
` <b-alert show>Default Alert</b-alert>`

Let me know if this helps.

**Comment by KylSanAntonio** [comment]
> Hi,
> 
> Thanks for the detailed information! Bootstrap Vue uses custom vue components to surface all of the bootstrap 4 components. While the css is shared between the two, all of the javascript is custom vue.
> 
> Please see the documentation for navbar and alert:
> https://bootstrap-vue.org/docs/components/alert
> https://bootstrap-vue.org/docs/components/navbar
> 
> For instance. Rather than:
> `<div class="alert alert-primary" role="alert">This is a primary alert—check it out!</div>`
> 
> You should use:
> ` <b-alert show>Default Alert</b-alert>`
> 
> Let me know if this helps.

Hi @GregYankovoy ,

At first I am using the code for bootstrap 3 but then when I tried to use bootsrap 4 the js is working. Thanks.
